---
- hosts: all
  vars_files:
    - vars.yml
  gather_facts: true
  become: yes

  tasks:
    - name: Set hostname
      hostname: name=www.lange-nacht-der-museen.de

    - name: Install system packages
      apt: pkg={{ item }} update-cache=yes
      with_items: "{{ system_packages }}"

    - name: Save ssh key to server
      copy: src={{ ssh_private_key }} dest=/root/.ssh/id_rsa mode=600

    - name: Create directory for app
      file: path={{ install_root }}/{{ project_name }} state=directory

    - name: Set Postfix option hostname
      debconf: name=postifx question="postfix/mailname" value="{{ ansible_fqdn }}" vtype="string"
      notify: restart postfix

    - name: Set Postfix option type as internet site
      debconf: name=postfix question="postfix/main_mailer_type" value="'Internet Site'" vtype="string"
      notify: restart postfix

    - name: Copy postfix config
      template: src=files/main.cf.j2 dest=/etc/postfix/main.cf
      notify: restart postfix

    - name: Configure MySql
      template: src=files/my.j2 dest=/etc/mysql/my.cnf
      notify: restart mysql

    - name: start mysql
      service: name=mysql state=started

    - name: create mysql database user
      mysql_user:
        name={{ db_user }}
        host={{ item }}
        password={{ db_password }}
        priv=*.*:ALL,GRANT
        state=present
        login_user=root
        login_password={{ db_root_password }}
      with_items:
        - 80.147.241.31
        - '{{ ansible_hostname }}'
        - '{{ ansible_default_ipv4["address"] }}'
        - 127.0.0.1
        - ::1
        - localhost

    - name: delete anonymous MySQL server user for $server_hostname
      mysql_user:
        user=""
        host="{{ ansible_hostname }}"
        state=absent
        login_user=root
        login_password={{ db_root_password }}

    - name: delete anonymous MySQL server user for localhost
      mysql_user:
        user=""
        state=absent
        login_user=root
        login_password={{ db_root_password }}

    - name: remove the MySQL test database
      mysql_db:
        db=test
        state=absent
        login_user=root
        login_password={{ db_root_password }}

    - name: create mysql database
      mysql_db: name={{ db_name }} login_host=localhost login_user={{ db_user }} login_password={{ db_password }} state=present

    - name: remove default nginx site
      file: path=/etc/nginx/sites-enabled/default state=absent

    - name: Set timezone variables
      copy: content='Europe/Berlin\n'
            dest=/etc/timezone
            owner=root
            group=root
            mode=0644
            backup=yes
      notify:
        - update timezone

  handlers:
    - name: restart mysql
      service: name=mysql state=restarted
    - name: restart postfix
      service: name=postfix state=restarted
    - name: update timezone
      command: dpkg-reconfigure --frontend noninteractive tzdata

- include: deploy.yml

# vim:ft=ansible:
