---
- hosts: all
  vars_files:
    - vars.yml
  gather_facts: false
  become: yes

  tasks:
    - name: Install system packages
      apt: pkg={{ item }} update-cache=yes
      with_items: "{{ system_packages }}"

    - name: Save ssh key to server
      copy: src={{ ssh_private_key }} dest=/root/.ssh/id_rsa mode=600

    - name: Create directory for app
      file: path={{ install_root }}/{{ project_name }} state=directory

    - name: Configure MySql
      template: src=files/my.j2 dest=/etc/mysql/my.cnf
      notify: restart mysql

    - name: start mysql
      service: name=mysql state=started

    - name: create mysql database user
      mysql_user: name={{ db_user }} password={{ db_password }} priv=*.*:ALL,GRANT state=present login_user=root login_password={{ db_root_password }}

    - name: create mysql database
      mysql_db: name={{ db_name }} login_host=localhost login_user={{ db_user }} login_password={{ db_password }} state=present

    - name: remove default nginx site
      file: path=/etc/nginx/sites-enabled/default state=absent

  handlers:
    - name: restart mysql
      service: name=mysql state=restarted

- include: deploy.yml

# vim:ft=ansible:
