---
# a unix path-friendly name (IE, no spaces or special characters)
project_name: langenacht

# the base path to install to. You should not need to change this.
install_root: /srv

# the python module path to your project's wsgi file. E.g. for a directory
# layout like this (assuming `langenacht` is the project_name and top level
# directory name):
# langenacht
# ├── apps
# ├── __init__.py
# ├── settings.py
# ├── urls.py
# ├── wsgi.py
# ├── manage.py
# └── requirements.txt
# the correct wsgi_module value would be `wsgi`
wsgi_module: wsgi

# any directories that need to be added to the PYTHONPATH.
pythonpath: "{{ install_root }}/{{ project_name }}/apps"

# the git repository URL for the project
project_repo: git@bitbucket.org:jetson/langenacht.git

# the git repository URL for jetson
jetson_repo: git@bitbucket.org:jetson/jetson.git

# a private key that has access to the repository URL
ssh_private_key: ~/.ssh/id_rsa

# The value of your django project's STATIC_ROOT settings.
# This will be the directory that django's `collectstatic` management command
# copies static files to, and it must be an absolute path. The default value
# here assumes that STATIC_ROOT is set in your settings.py like so:
# STATIC_ROOT = os.path.abspath(os.path.join(BASE_DIR, 'static'))
static_root: "{{ install_root }}/{{ project_name }}/static"

# the dns name or names (space separated) for your server
server_name: lange-nacht-der-museen.de www.lange-nacht-der-museen.de

# database setup. We use local password-based authentication for
# mysql and thus you need to provide a username and password, and your
# settings.py MUST set "localhost" or "127.0.0.1" as the HOST value. For
# example, the default settings here assume the following values in
# settings.py:
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'HOST': 'localhost',
#         'NAME': 'langenacht',
#         'USER': 'langenacht',
#         'PASSWORD': 'changeme',
#     }
# }
db_name: langenacht
db_user: langenacht
db_password: changeme
db_root_password: 'changemeroot'

# apt packages, you should not need to change this unless you have packages
# listed in your requirements.txt that depend on system packages.
system_packages:
  - git
  - nginx
  - gunicorn
  - mysql-server
  - mysql-client
  - libmysqlclient-dev
  - python-mysqldb
  - python-pip
  - python-dev
  - memcached
  - libmemcached-dev
  - mailutils
  - unzip

# vim:ft=ansible:
